### ISSUE TITLE
Question , may be not a bug , takes too long time to build

### ISSUE THREAD

**Issue by qindj** [LongDirtyAnimAlf/fpcupdeluxe#276] opened 2020-07-15 07:16 UTC
![image](https://user-images.githubusercontent.com/1707762/87515025-c251bd00-c6ad-11ea-83a8-49125bf06f9a.png)

Hi ,Admin

just upgrade to 1.80 , try to build trunk version of both fpc & lazarus

plz look at the attached screenshot, takes more than 4 hours, it that normal? 

in ui, it shows: 
(1002) Target OS: Win64 for x64
(3104) Compiling fcllaz.pas
(3104) Compiling lazaruspackageintf.pas

env: Windows 10 x64

**Comment by qindj** [comment] 2020-07-15 07:18
Sorry, "正在运行" means "Running"

**Comment by qindj** [comment] 2020-07-15 10:10
now it's over 7 hours , tried close / restart / clean previous built , same result

**Comment by LongDirtyAnimAlf** [comment] 2020-07-18 06:12
This is definitely not normal ! But the cause of this this issue is unknown to me. As is its relation with fpcupdeluxe.
I have never seen this. And I am mot able to reproduce. Therefor, I am closing due to the fact that I will never be able to solve.
If you have more info, you may re-open or post your own solution for this.

**Closed by LongDirtyAnimAlf** 2020-07-18 06:12 UTC

**Comment by qindj** [comment] 2020-07-18 10:20
sure, i'll do more tests next week.

**Comment by qindj** [comment] 2020-07-21 04:02
tested & works now.

i did:
1. delete all files and folders of fpc & lazarus
2. restart computer
3. close all applications except fpcupdeluxe
