### ISSUE TITLE
OpenBSD version cannot download fpc.zip

### ISSUE THREAD

**Issue by Alexey-T** [LongDirtyAnimAlf/fpcupdeluxe#191] opened 2020-03-22 13:26 UTC
This URL is valid but app cannot get it
![eee](https://user-images.githubusercontent.com/4154978/77250572-ebab9080-6c59-11ea-8ce9-76b10e277c8f.png)

**Comment by LongDirtyAnimAlf** [comment] 2020-03-24 17:00
Please test.

https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/tag/1.6.8e

**Comment by Alexey-T** [comment] 2020-03-24 17:24
App show another version? With f ?

**Comment by Alexey-T** [comment] 2020-03-24 17:48
Not fixed
```

Going to install/update FPC only with given options.
FPCUP(deluxe) is starting up.

Bootstrap dir:         /home/user/fpcupdeluxe/fpcupdeluxe/fpcbootstrap
FPCupdeluxe basedir:   /home/user/fpcupdeluxe/fpcupdeluxe
FPC URL:               ftp://ftp.freepascal.org/pub/fpc/snapshot/v32/source/fpc.zip
FPC options:            -Fl/usr/local/lib -Fl/usr/pkg/lib
FPC source directory:  /home/user/fpcupdeluxe/fpcupdeluxe/fpcsrc
FPC install directory: /home/user/fpcupdeluxe/fpcupdeluxe/fpc
Lazarus URL:           https://svn.freepascal.org/svn/lazarus/tags/lazarus_2_0_6
Lazarus options:        -Fl/usr/local/lib -Fl/usr/X11R6/lib -Fl/usr/pkg/lib -Fl/usr/X11R7/lib
Lazarus directory:     /home/user/fpcupdeluxe/fpcupdeluxe/lazarus

Please stand back and enjoy !

fpcupdeluxe: info: 21-3-20 10:44:17: fpcupdeluxe: V205 (20200324) started.
fpcupdeluxe: info: FPCUPdeluxe V1.6.8f for x86_64-openbsd running on openbsd 6.6 6.6
fpcupdeluxe: info: FPCNativeInstaller (CleanModule: FPC): No FPC source directory (/home/user/fpcupdeluxe/fpcupdeluxe/fpcsrc) found [yet] ... nothing to be done
fpcupdeluxe: WARNING: FPCNativeInstaller (GetModule: FPC): Using FTP for download of FPC sources.
fpcupdeluxe: info: FPCNativeInstaller (DownloadFromFTP: FPC): Getting FPC sources.
fpcupdeluxe: info: FPCNativeInstaller (GetFile): Downloading ftp://ftp.freepascal.org/pub/fpc/snapshot/v32/source/fpc.zip
fpcupdeluxe: info: FPCNativeInstaller (GetFile): Could not download file with URL ftp://ftp.freepascal.org/pub/fpc/snapshot/v32/source/fpc.zip into /home/user/fpcupdeluxe/fpcupdeluxe/tmp (filename: FPCUPTMP00000.zip)


ERROR: Fpcupdeluxe fatal error !
```

**Comment by Alexey-T** [comment] 2020-03-24 17:49
date is wrong on that OS.

**Comment by LongDirtyAnimAlf** [comment] 2020-03-24 20:20
I cannot reproduce. So closing due to the fact that I cannot solve this.

**Closed by LongDirtyAnimAlf** 2020-03-24 20:20 UTC
