### ISSUE TITLE
Windows high-DPI GUI issues

### ISSUE THREAD

**Issue by Bi0T1N** [LongDirtyAnimAlf/fpcupdeluxe#140] opened 2019-08-03 12:23 UTC
Hello,
seems there is an issue for high-DPI devices. Main issues are the small textsize in the dark window and the setup+ buttons for patch. (see attached screenshots)

> Windows 10 default settings (Surface Pro 4):
> - Scaling: 200% (recommended)
> - Resolution: 2736x1824 (recommended)

![fpcupdeluxe](https://user-images.githubusercontent.com/28802083/62411852-d9f97800-b5f9-11e9-8de8-1a3b9ec71786.jpg)
setup+ window standard:
![fpcupdeluxe_setup](https://user-images.githubusercontent.com/28802083/62411770-9fdba680-b5f8-11e9-9875-579fad3b2fad.jpg)
setup+ window sized:
![fpcupdeluxe_setup-sized ](https://user-images.githubusercontent.com/28802083/62411771-9fdba680-b5f8-11e9-9f18-d781019c6b60.jpg)

**Comment by LongDirtyAnimAlf** [comment] 2020-12-11 09:15
Would you mind testing the latest pre-release ?
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/tag/1.8.2g

You can change the font-size in the main windows by press ctrl-left and the scrolling with scroll-wheel.

Sorry for my late reply.

**Comment by Bi0T1N** [comment] 2020-12-11 13:08
Increasing the fontsize seems to work fine and is also kept for restarts of the application (see attached screenshot).
![fontsize_scrolling](https://user-images.githubusercontent.com/28802083/101906983-beb95800-3bb1-11eb-99d9-53b1b2d9e6c3.PNG)
The other layout issues are still there.

**Comment by LongDirtyAnimAlf** [comment] 2020-12-11 13:16
Can you please show me the Setup+ screen also ?
Thanks.

**Comment by LongDirtyAnimAlf** [comment] 2020-12-11 14:16
New binaries.
Should now be high-DPI aware.
Please test again. Thanks.

**Comment by Bi0T1N** [comment] 2020-12-11 15:42
> Can you please show me the Setup+ screen also ?  

The previous Setup+ was the same as on the old screenshots.

> New binaries.
> Should now be high-DPI aware.
> Please test again. Thanks.

Looks much better now - only the directory folder isn't shown correctly.
![startup](https://user-images.githubusercontent.com/28802083/101918898-d993c880-3bc1-11eb-8b1a-2f2791f76dbd.PNG)
![setup-window](https://user-images.githubusercontent.com/28802083/101918907-dc8eb900-3bc1-11eb-8188-0d452bf45fc9.PNG)
However, after restarting the application it behaves a bit strange. If you close it while it is shown in full screen it starts in a small window.
![fullscreen_to_small_restart](https://user-images.githubusercontent.com/28802083/101919219-37281500-3bc2-11eb-9e6c-3e6abbb3c2b9.PNG)
After another restart the window size is changed again with the lower part not visible:
![second_restart](https://user-images.githubusercontent.com/28802083/101919425-70608500-3bc2-11eb-913e-9bfe0d447e03.PNG)
The third restart is shown in the following and it always starts in that position now.
![third_restart](https://user-images.githubusercontent.com/28802083/101923337-2cbc4a00-3bc7-11eb-8725-d9e2f6be345c.PNG)

**Comment by LongDirtyAnimAlf** [comment] 2020-12-11 15:53
Good info.
Will try to resolve this.

**Comment by LongDirtyAnimAlf** [comment] 2020-12-12 11:00
Latest release should be the best possible handling of High DPI.
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/tag/1.8.2g

I am closing this issue.
There is nothing more I can do.
All DPI issues remaining are caused by the limitations of Lazarus.
If you do know of any more improvements, please re-open.

**Closed by LongDirtyAnimAlf** 2020-12-12 11:00 UTC
