### ISSUE TITLE
Wrong "Found system wide libQt5Pas.so and that will be used." on SteamOS / Steam Deck

### ISSUE THREAD

**Issue by BeRo1985** [LongDirtyAnimAlf/fpcupdeluxe#537] opened 2022-09-25 01:20 UTC
At my ArchLinux-based readonly root-fs Linux system (Steam Deck) "without" system-wide libQt5pas.so, fpcupdeluxe outputs the message "Wrong "Found system wide libQt5Pas.so and that will be used.", but it is wrong. It's in the same local directory like the fpcupdeluxe-x86_64-linux-qt5 binary itself, and not under /usr/lib, /usr/local/lib, or whatever on the root-fs . So please fix the LibWhich function in the fpcuputil.pas, so that one can also use fpcupdeluxe on the Steam Deck in the Desktop mode of SteamOS for buildung Lazarus. GTK2 is not possible, since SteamOS has no libraries for GTK2 in its root-fs, so QT5 is needed here. And I do want to avoid `sudo steamos-readonly disable` since it can break SteamOS updates and otherwise at a successful SteamOS update, all changes on the root-fs will be gone also otherwise.  

So again, please fix the LibWhich function in the fpcuputil.pas or at least please add a Use-Qt5-trickery override function as checkbox in the Setup+ dialog or something like that.

**Comment by LongDirtyAnimAlf** [comment] 2022-09-25 11:47
Correct.
Please test.
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/download/v2.2.0k/fpcupdeluxe-x86_64-linux-qt5
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/download/v2.2.0k/fpcupdeluxe-x86_64-linux-qt5.zip

**Comment by BeRo1985** [comment] 2022-09-25 13:06
Sadly still

![image](https://user-images.githubusercontent.com/428863/192144948-1b4144a4-34ac-4659-8c1a-ca6d9b8972a0.png)

**Comment by LongDirtyAnimAlf** [comment] 2022-09-25 13:50
Using which is not good for finding a library. Which looks for a file in the path.
Libraries might be outside the path. And that might be the case on your system.
Would you please check that also ?
(move the libQt5Pas.so files to a local directory in your home directory, so the do not reside next to fpcupdeluxe)

**Comment by LongDirtyAnimAlf** [comment] 2022-09-25 13:52
If fpcupdeluxe runs without libqt5 next to it, there is another location on your system that holds this library.

**Comment by BeRo1985** [comment] 2022-09-25 14:12
I've already tried that. Then fpcupdeluxe fails to start with a error message to the console that libQt5Pas.so.1 isn't found. So there is 100% no system-wide libQt5Pas .

**Comment by BeRo1985** [comment] 2022-09-25 14:15
See

![image](https://user-images.githubusercontent.com/428863/192148263-5dd5edee-aa87-4de0-a67e-c476fd278ad9.png)

**Comment by LongDirtyAnimAlf** [comment] 2022-09-28 12:42
Please test new release. Thanks.
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/tag/v2.2.0m

About linking.
I am a regular user of arch linux. Would it be sufficient to install arch and try to reproduce your issue ?

**Comment by BeRo1985** [comment] 2022-09-28 13:37
Rather no, because I had to install SteamOS again afterwards then, and set everything up again from scratch. Because only under SteamOS the SteamDeck hardware is used optimally. Even Windows 11 runs on the SteamDeck only with umpteen restrictions. The SteamDeck is basically an x86-64 PC in a Switch-like form factor, but with countless custom components, such as a PS5/XBox-like AMD Custom Zen2 + RDNA2 APU, which are not otherwise available on the market. So far, this hardware is only fully supported under SteamOS, and only incompletely under other Linux distros and Windows.

But I will test the new build in the next night or evening.

**Comment by LongDirtyAnimAlf** [comment] 2022-09-29 05:51
This tells me that it is based on Debian ?
https://store.steampowered.com/steamos

I have build the libQt5Pas many times before. On many systems. I think I can help.

**Comment by BeRo1985** [comment] 2022-09-29 08:58
The older SteamOS 1 and 2 versions were Debian-based, but from SteamOS 3 on it is based on ArchLinux, see https://en.wikipedia.org/wiki/SteamOS and https://www.reddit.com/r/SteamDeck/comments/olgd8s/why_the_change_from_debian_to_arch_linux_for/ . So the store version from SteamOS maybe then the wrong one, the older one. So, you do need to see then, if it is already SteamOS 3 or still SteamOS 2. At least the Steam Deck mobile gaming consoles are coming preinstalled with SteamOS 3.x.

And I'll test the binary today now.

**Comment by LongDirtyAnimAlf** [comment] 2023-02-20 12:43
Closing due to no feedback.
Please re-open when needed.

**Closed by LongDirtyAnimAlf** 2023-02-20 12:43 UTC
