### ISSUE TITLE
Error: Illegal parameter: -Twin32

### ISSUE THREAD

**Issue by terrylao** [LongDirtyAnimAlf/fpcupdeluxe#393] opened 2021-06-24 09:56 UTC
when i try to install my packages, in x86-win64.
if i just click compile, everything goes good. i also have install i386-win32 and x86_64-linux
but when i click install, it shows me 
Error: Illegal parameter: -Twin32
Hint: -? writes help pages
Verbose: C:\fpcupdeluxe\fpc\bin\x86_64-win64\ppcx64.exe returned an error exitcode
Verbose: [lazarus.exe] Error 1
Verbose: make.exe[2]: Leaving directory `C:/fpcupdeluxe/lazarus/ide'

**Comment by LongDirtyAnimAlf** [comment] 2021-06-24 10:48
You also have to set the CPU to i386.

**Comment by terrylao** [comment] 2021-06-24 10:59
where to set?

**Comment by LongDirtyAnimAlf** [comment] 2021-06-24 13:23
![aaaaaaaa](https://user-images.githubusercontent.com/10783972/123270314-1856f380-d500-11eb-8c9f-155e619ac811.JPG)

**Comment by terrylao** [comment] 2021-06-24 13:47
[image: image.png]
we have different screen.

**Comment by LongDirtyAnimAlf** [comment] 2021-06-24 13:51
Your image is not visible for me unfortunately.

**Comment by terrylao** [comment] 2021-06-24 13:57
[image: package2.png]
[image: package1.png]
please check this out.

**Comment by LongDirtyAnimAlf** [comment] 2021-06-24 14:23
![aanoimage](https://user-images.githubusercontent.com/10783972/123279780-77206b00-d508-11eb-8aa6-8eb179d32539.JPG)

**Comment by terrylao** [comment] 2021-06-24 22:32
how about this.

**Comment by LongDirtyAnimAlf** [comment] 2021-06-25 06:08
Pictures are visible now. Thanks.
You are setting the package options. That is not needed. You need to look into the project options.
As you have installed a win64 version of Lazarus and FPC, all project settings need to be set to default to install a package.
After installation, you can again set the CPU and OS target in the project options.

**Comment by terrylao** [comment] 2021-06-25 07:02
all my project was setting to "default"
![未命名](https://user-images.githubusercontent.com/8318854/123383779-2c652880-d5c6-11eb-9b50-8d524a5ad7b8.png)

as i use lazarus IDE, every packages installation are work.

**Comment by LongDirtyAnimAlf** [comment] 2021-06-25 08:29
Have a look at your idemake.cfg file inside the config_lazarus directory.
See is there is a Twin32 define.
If so, remove it (without Lazarus running).
If not, please post the contents of this file.

**Comment by terrylao** [comment] 2021-06-25 08:57
yes, there is a define "Twin32 "
when i remove it without Lazarus running, and run lazarus, i also cannot do installtion, and with same time, will add "Twin32 " again.
my idemake.cfg below:
[idemake.zip](https://github.com/LongDirtyAnimAlf/fpcupdeluxe/files/6714892/idemake.zip)

**Comment by LongDirtyAnimAlf** [comment] 2021-08-16 14:20
Closing.
Unable to reproduce. Unable to solve. Sorry about this.

**Closed by LongDirtyAnimAlf** 2021-08-16 14:20 UTC

**Comment by terrylao** [comment] 2021-08-16 23:52
i have met not just this strange,
also install the newest stable 3.3.1 and 2.1.0 , and running the TRegex got SigSeg
but same code in 3.2.2 and 2. 0.12 works fine.

**Comment by LongDirtyAnimAlf** [comment] 2021-08-17 08:06
That are FPC and Lazarus issues. You need to have a fitting FPC for the Lazarus version of your choice.
And that might change by the day.
