### ISSUE TITLE
Cross compiling to IOS

### ISSUE THREAD

**Issue by han-k59** [LongDirtyAnimAlf/fpcupdeluxe#624] opened 2023-09-18 18:36 UTC
I noted that I can't install the cross compiler Linux to iOS. It used to work (at least it compiled but executable never tested). 

Not so important but is this easy to fix? See log below 

Han

Looking for FPCUPdeluxe cross-tools on GitHub (if any).
Going to look for the right cross-libraries. Can (will) take some time !
Looking for: IOS_All.zip
No luck in getting then cross-tools ... aborting.

**Comment by LongDirtyAnimAlf** [comment] 2023-09-29 10:22
Are you using the latest version of fpcupdeluxe ?
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/tag/v2.4.0a

**Comment by han-k59** [comment] 2023-09-29 11:59
Yes V2.4.0a

**Comment by LongDirtyAnimAlf** [comment] 2023-10-21 05:50
The libs are here.
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/download/crosslibs_all/IOS_All_IOS_1307.zip
You can get them and unpack them in the right directory.

This error is caused by the fact that fpcupdeluxe is moving towards a more unified system of getting tools and libs. This is an erroro caused by that transition not being finished yet.

**Comment by winddriver** [comment] 2023-11-05 09:51
The same problem exists on windows, unable to install iOS cross compile environment
Has been decompressed  "IOS_All_IOS_1307.zip", do not know the location is right?

![image](https://github.com/LongDirtyAnimAlf/fpcupdeluxe/assets/3221597/3e28edfa-fd99-4462-a921-c8708080723e)
![image](https://github.com/LongDirtyAnimAlf/fpcupdeluxe/assets/3221597/5ca7cace-6d3a-494d-9e73-f76fb902085d)

**Comment by winddriver** [comment] 2023-11-05 10:23
2.4.0Bp installed the iOS cross-compilation environment successfully
![image](https://github.com/LongDirtyAnimAlf/fpcupdeluxe/assets/3221597/b77662c1-e79c-4617-a3e2-ad2dc05058e8)

**Comment by LongDirtyAnimAlf** [comment] 2024-01-22 15:32
Thanks for reporting.
Closing.

**Closed by LongDirtyAnimAlf** 2024-01-22 15:32 UTC
Labels: bug
