### ISSUE TITLE
Cross compilation error

### ISSUE THREAD

**Issue by pony5551** [LongDirtyAnimAlf/fpcupdeluxe#110] opened 2019-03-22 18:25 UTC
OS: win64
To compile the Linux

C:\fpcupdeluxe\cross\bin\x86_64-linux\x86_64-linux-ld.exe: cannot find /lib64/ld-linux-x86-64.so.2

**Comment by mdbs99** [comment] 2019-03-22 20:32
Here it's working.
Have you tried clean /lib files and "Auto update compilers"?

**Comment by pony5551** [comment] 2019-03-22 20:49
> Here it's working.
> Have you tried clean /lib files and "Auto update compilers"?

I did, but there was still a problem!

**Comment by pony5551** [comment] 2019-03-22 20:51
My FPC: trunkgit

My laz: trunkgit


I also tried

FPC: fixes_3_2

Laz: fixes_2_0

**Comment by pony5551** [comment] 2019-03-22 21:01
C:\fpcupdeluxe\cross\bin\x86_64-linux\x86_64-linux-ld.exe: cannot find /lib64/ld-linux-x86-64.so.2

Why is the path here /lib64/ld-linux-x86-64.so.2

The prompt when the cross-compiler installation is complete looks like this:
Fpcupdeluxe: FPC cross-builder: Building compiler for linux-x86_64.
fpcupdeluxe: info: FPC x86_64-linux cross-builder: Detected source version FPC (compiler): 3.3.1
fpcupdeluxe: info: TAny_linux-x86_64: Found correct binary utilities in directory C:\fpcupdeluxe\cross\bin\x86_64-linux
fpcupdeluxe: info: TAny_linux-x86_64: Found correct library in directory C:\fpcupdeluxe\cross\lib\x86_64-linux
fpcupdeluxe: info: FPC x86_64-linux cross-builder: Using compiler with version: 3.3.1
fpcupdeluxe: Done !!

**Comment by mdbs99** [comment] 2019-03-22 23:21
Are you on Windows?
My fpcupdeluxe version is i386-win32 1.6.2g
I can compile from Windows to Linux - I believe it's your case.

So, try to reinstall using this version. Pay attention: I use the 32-bit version. But it allow me generate 64-bit as well.
Finally, you install 32-bit cross-linux and than 64-bit.

**Comment by pony5551** [comment] 2019-03-23 01:08
Sorry, I forgot the important point, library project1 compile error;

**Comment by LongDirtyAnimAlf** [comment] 2019-03-23 09:42
Unfortunately, I cannot reproduce your problem.
You are on Win64.
Do you use:
fpcupdeluxe 32 bit
or
fpcupdeluxe 64 bit

**Comment by pony5551** [comment] 2019-03-23 13:32
i use the fpcupdeluxe 64 bit

**Comment by pony5551** [comment] 2019-03-23 21:04
I also tested _fpcupdeluxe-i386-win32.exe_, but the same problem!

**Comment by Kashaket** [comment] 2019-06-01 20:04
> I also tested _fpcupdeluxe-i386-win32.exe_, but the same problem!

Hello, now  it has gone;
I've tried different configurations, and the only thing i can say, that this feature has been broken, and then repaired after a while.
However, GTK3 still doesn't work with Win64 Cross-Compiler, only with Win32 somehow...
 It is fpc problem, i think.
Just try to update your compiler

Best regards,
Andrew

**Comment by LongDirtyAnimAlf** [comment] 2019-12-11 12:25
Related:

https://github.com/LongDirtyAnimAlf/fpcupdeluxe/issues/161

**Comment by LongDirtyAnimAlf** [comment] 2019-12-25 07:44
Would you mind trying the latest release of fpcupdeluxe ?

Please use it to update FPC.
It will patch the FPC sources, so cross-linking of a library will succeed.
Please test of the resulting library works on the target system.

Thanks.

**Comment by LongDirtyAnimAlf** [comment] 2020-02-27 18:04
Closing due to no feedback.
Please re-open when needed.

**Closed by LongDirtyAnimAlf** 2020-02-27 18:04 UTC
