### ISSUE TITLE
Error linking Lazarus (fpcupdeluxe v2.4.0bp with base glibc versioning)

### ISSUE THREAD

**Issue by WayneSherman** [LongDirtyAnimAlf/fpcupdeluxe#634] opened 2023-11-05 21:44 UTC
Testing fpcupdeluxe-x86_64-linux v2.4.0bp with base glibc versioning
Distro:  Manjaro Linux 64-bit with XFCE desktop and latest updates
libc version:  2.38
Building FPC stable and Lazarus stable
For each test, I am using a new empty install folder
Every settings is left at the default except as mentioned below.

1) Building with glibc symbol versioning disabled
(Setup+ | Misc Settings | Force linking against lowest @GLIBC-version = unchecked)
fpc stable and Lazarus stable build without errors

2) Building with glibc symbol versioning enabled
(Setup+ | Misc Settings | Force linking against lowest @GLIBC-version = checked)
fpc stable builds without errors
**Building Lazarus stable has a link error:**

```
/usr/bin/make --assume-new=lazarus.pp lazarus OPT=' @/home/test/fpcupdeluxe/config_lazarus/idemake.cfg'
/home/test/fpcupdeluxe/fpc/bin/x86_64-linux/fpccompat.sh -gl -vbqewnhi -Sci -dlclgtk2 -Fu../designer -Fu../debugger -Fu../debugger/frames -Fu../converter -Fu../packager -Fu../packager/frames -Fu../components/custom -Fuframes -Fu. -Fu/home/test/fpcupdeluxe/fpcsrc/rtl -Fu/home/test/fpcupdeluxe/fpcsrc/packages/paszlib -Fu/home/test/fpcupdeluxe/fpcsrc/packages/fcl-process -Fu/home/test/fpcupdeluxe/fpcsrc/packages/hash -Fu/home/test/fpcupdeluxe/fpcsrc/packages/libtar -Fu/home/test/fpcupdeluxe/fpcsrc/packages/fpmkunit -Fu/home/test/fpcupdeluxe/fpcsrc/packages/regexpr -Fiinclude -Fiinclude/linux -Fi../images -FE.. -FU../units/x86_64-linux/gtk2 -Cg -Fl/usr/lib/gcc/x86_64-pc-linux-gnu/13.2.1 @/home/test/fpcupdeluxe/config_lazarus/idemake.cfg -dx86_64 lazarus.pp
(1002) Target OS: Linux for x86-64
(3104) Compiling lazarus.pp
(9022) Compiling resource /home/test/fpcupdeluxe/lazarus/units/x86_64-linux/gtk2/lazarus.or
(9015) Linking ../lazarus
/usr/bin/ld: /home/test/fpcupdeluxe/lazarus/components/fpdebug/lib/x86_64-linux/fpdbglinuxextra.o: in function `FPPTRACE':
/home/test/fpcupdeluxe/lazarus/components/fpdebug//fpdbglinuxextra.pas:98:(.text.n_fpdbglinuxextra_$$_fpptrace$longint$longint$pointer$pointer$$int64+0x41): undefined reference to `FPC_SYSCALL4'
make[1]: *** [Makefile:5105: idepkg] Error 2
make: *** [Makefile:3827: idepkg] Error 2
/home/test/fpcupdeluxe/lazarus/ide/lazarus.pp(167,1) Error: (9013) Error while linking
/home/test/fpcupdeluxe/lazarus/ide/lazarus.pp(167,1) Fatal: (10026) There were 1 errors compiling module, stopping
Fatal: (1018) Compilation aborted
Error: /home/test/fpcupdeluxe/fpc/bin/x86_64-linux/ppcx64 returned an error exitcode
Error: (lazarus) Build IDE: stopped with exit code 2
Error: (lazarus) Building IDE: Building IDE failed.

fpcupdeluxe: ERROR: Universal Installer (ConfigModule: fpdebug): lazbuild returned error code 512
Details: 
ERROR: Fpcupdeluxe fatal error !
Sequencer (fpdebug): Failure running fpcupdeluxe: error executing sequence fpdebug
Sequencer (UniversalDefault): Failure running fpcupdeluxe: error executing sequence UniversalDefault
Sequencer (Lazarus): Failure running fpcupdeluxe: error executing sequence Lazarus
Sequencer (Default): Failure running fpcupdeluxe: error executing sequence Default
```

Is this error related to this patch?
glibc_debugger_trunk.patch [[LINK](https://github.com/LongDirtyAnimAlf/fpcupdeluxe/blob/f23ff3033a0aaf21601d9c4ebbebc08e8b344154/patches/patchlazarus/glibc_debugger_trunk.patch#L15)]

**Comment by LongDirtyAnimAlf** [comment] 2023-11-07 13:18
That is correct. This is reported in the Lazarus bug-tracker.
https://gitlab.com/freepascal.org/lazarus/lazarus/-/issues/40575
And waiting for approval.

**Comment by WayneSherman** [comment] 2023-11-07 18:46
Since I am testing stable/stable this patch is not used:  glibc_debugger_trunk.patch

Lazarus compiles and links successfully until the lazdebuggerfp package is added, and rebuilding is attempted.
```
fpcupdeluxe: info: Universal Installer (GetModule: fpdebug): Getting module fpdebug.
fpcupdeluxe: info: Universal Installer (GetModule: fpdebug): No fpdebug patches defined.
fpcupdeluxe: info: Universal Installer (InstallPackage): Installing lazdebuggerfp version 1.
...
fpcupdeluxe: info: Universal Installer (ConfigModule: fpdebug): Packages were installed.
fpcupdeluxe: info: Universal Installer (ConfigModule: fpdebug): Going to rebuild Lazarus.

```

I suspect that changing the Setup+ option to force linking against lowest glibc is not causing a failure because of the glibc patch or the -XLC option.  I think the failure is because "-dFPC_USE_LIBC" is added as a build option for FPC. [[LINK](https://github.com/LongDirtyAnimAlf/fpcupdeluxe/blob/f23ff3033a0aaf21601d9c4ebbebc08e8b344154/sources/installerfpc.pas#L2214)]

What is the purpose of defining "FPC_USE_LIBC" when building the FPC compiler?

Building FPC with "-dFPC_USE_LIBC" appears to expose a bug in Lazarus which is unrelated to the glibc version patch.  fpdbglinuxextra.pas [[LINK](https://gitlab.com/freepascal.org/lazarus/lazarus/-/blob/fb8756e03b6255a41253af6b14e83d3253bf42af/components/fpdebug/fpdbglinuxextra.pas#L72-73
)] is looking for an external symbol FPC_SYSCALL4.  But it isn't there because syscall.inc was not included [[LINK](https://gitlab.com/freepascal.org/fpc/source/-/blob/5205ce30f4fd31e56701aa9bc09ae2b56a79dede/rtl/linux/sysos.inc#L61-71)] and syscall.inc is what exports FpSysCall ... [public,alias:'FPC_SYSCALL4'] [[LINK](https://gitlab.com/freepascal.org/fpc/source/-/blob/5205ce30f4fd31e56701aa9bc09ae2b56a79dede/rtl/linux/x86_64/syscall.inc#L125)].

**Comment by sgmihai** [comment] 2023-12-25 14:31
I am getting the same error apparently, using latest 2.4.0c -qt5: https://pastebin.com/p4zL2FYq
If I get the gtk2 fpcupdeluxe, it works, and lazarus with gtk2 builds. But I want to use the qt5 one, since I am on plasma desktop and gtk2 is ancient now. Any ideas ? And where is the qt6 build, can't see it on latest releases ?

**Comment by LongDirtyAnimAlf** [comment] 2023-12-26 09:13
The error you see is caused by this : QTimer_singleShot3 definition not found. This is caused by a bad libQt5Pas.so. I will look into this.
I will also look into QT6.

**Comment by LongDirtyAnimAlf** [comment] 2023-12-26 10:58
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/download/v2.4.0c/fpcupdeluxe-x86_64-linux-qt6.zip
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/download/v2.4.0c/fpcupdeluxe-x86_64-linux-qt6

**Comment by sgmihai** [comment] 2024-01-09 01:51
Still getting that error on latest release version. My distro is archlinux, used the official qt5pas package https://archlinux.org/packages/extra/x86_64/qt5pas/ - currently flagged as out of date.
I tried the latest qt6 version but the end result is a gtk2 built Lazarus. I couldn't find any setting to change the widget set used to build Lazarus. I used qt6pas from here https://builds.garudalinux.org/repos/chaotic-aur/x86_64/qt6pas-6.2.7-2-x86_64.pkg.tar.zst
 Any ideas?

**Comment by LongDirtyAnimAlf** [comment] 2024-01-22 15:25
As this is an ongoing effort regarding FPC and Lazarus, and not related to fpcupdeluxe, I am closing this issue.
Please be informed that FPC and Lazarus developers are working to get this corrected. Expect a fix the next few months.

**Closed by LongDirtyAnimAlf** 2024-01-22 15:25 UTC
