### ISSUE TITLE
Win64 -> Darwinx64 crosscompilation error about AS

### ISSUE THREAD

**Issue by synopse** [LongDirtyAnimAlf/fpcupdeluxe#111] opened 2019-03-22 22:20 UTC
I have installed latest `fpcupdeluxe-i386-win32.exe` and setup the cross-compilers.

All targets work, except x86_64-darwin.
```
  <Compiler Value="C:\np\fpc\bin\i386-win32\fpc.exe" Date="1312572699"/>
  <Params Value=" -Tdarwin -Px86_64 -MDelphi -Scaghi -CX -Ci -O2 -XX -l -vewibq -vn-h- -FiD:\Dev\Lib -FiD:\Dev\Lib\SQLite3\fpc\lib\x86_64-darwin -FlD:\Dev\Lib\static\x86_64-darwin -FuD:\Dev\Lib -FuD:\Dev\Lib\SQLite3\DDD\dom -FuD:\Dev\Lib\SQLite3\DDD\infra -FuD:\Dev\Lib\SQLite3\ -FUD:\Dev\Lib\SQLite3\fpc\lib\x86_64-darwin\ -FED:\Dev\Lib\SQLite3\fpc\bin\x86_64-darwin\ -oD:\Dev\Lib\SQLite3\fpc\bin\x86_64-darwin\TestSQL3 -dFPC_NO_DEFAULT_MEMORYMANAGER -dFPC_CMEM TestSQL3.dpr"/>
  <Complete Value="False"/>

Compile Project, Mode: darwin64, OS: darwin, CPU: x86_64, Target: fpc\bin\x86_64-darwin\TestSQL3: Exit code 1, Errors: 1, Warnings: 123
Warning: Option "-Xr" is ignored for the current target platform.
Verbose: Free Pascal Compiler version 3.3.1-r40491 [2019/03/22] for x86_64
Verbose: Copyright (c) 1993-2018 by Florian Klaempfl and others
Verbose: Target OS: Darwin for x86_64
Verbose: Compiling TestSQL3.dpr
...
Verbose: Assembling syncommons
Debug: clang: warning: argument unused during compilation: '-mlinker-version=274.2'
Debug: clang: warning: argument unused during compilation: '-isystem /cygdrive/C//np/cross/bin/x86-darwin/include/clang/4.0.1/include'
Debug: clang: warning: argument unused during compilation: '-isysroot /cygdrive/C//np/cross/bin/x86-darwin/../../lib/x86-darwin/MacOSX10.11.sdk'
Debug: clang: warning: argument unused during compilation: '-cxx-isystem /cygdrive/C//np/cross/bin/x86-darwin/../../lib/x86-darwin/MacOSX10.11.sdk/usr/include/c++/4.2.1'
Debug: clang: warning: argument unused during compilation: '-cxx-isystem /cygdrive/C//np/cross/bin/x86-darwin/../../lib/x86-darwin/MacOSX10.11.sdk/usr/include/c++/4.2.1/x86_64-apple-darwin15'
Debug: clang: warning: argument unused during compilation: '-cxx-isystem /cygdrive/C//np/cross/bin/x86-darwin/../../lib/x86-darwin/MacOSX10.11.sdk/usr/include/c++/4.2.1/backward'
Debug: clang: warning: argument unused during compilation: '-Wno-liblto'
Debug: D:\Dev\Lib\SQLite3\fpc\lib\x86_64-darwin\SynCommons.s:7800:2: error: invalid instruction mnemonic 'cvtsi2sdl'
Debug:         cvtsi2sdl       %eax,%xmm0
Debug:         ^~~~~~~~~
Debug: D:\Dev\Lib\SQLite3\fpc\lib\x86_64-darwin\SynCommons.s:44305:2: error: invalid instruction mnemonic 'cvtsi2sdl'
Debug:         cvtsi2sdl       (%rsp),%xmm1
Debug:         ^~~~~~~~~
Debug: D:\Dev\Lib\SQLite3\fpc\lib\x86_64-darwin\SynCommons.s:44357:2: error: invalid instruction mnemonic 'cvtsi2sdl'
Debug:         cvtsi2sdl       (%rsp),%xmm0
Debug:         ^~~~~~~~~
SynCommons.pas(66656,0) Error: Error while assembling exitcode 1
SynCommons.pas(66656,0) Verbose: There were 2 errors compiling module, stopping
Verbose: Compilation aborted
Verbose: C:\np\fpc\bin\i386-win32\ppcrossx64.exe returned an error exitcode
``` 

It sounds like if the x86_64-apple-darwin15AS.exe cross-assembly doesn't support SSE2.
Close to https://bugs.freepascal.org/view.php?id=32324

Is there any missing command line flag?
I tried to add ` -CfSSE64` with no luck.

**Comment by LongDirtyAnimAlf** [comment] 2019-03-23 09:21
Thanks for pointing me towards the bug-report.

I have updated the Darwin binary tools to use clang 5.0
Please delete  "fpcupinstalldir\cross\bin\x86-darwin"
And rerun fpcupdeluxe to build the Darwin cross-compiler.
It should work (at least, it does on my system).

**Comment by mdbs99** [comment] 2019-03-23 20:12
In my case, I still use clang-4.0.exe and it works. How is that?

**Comment by synopse** [comment] 2019-03-25 09:46
I updated the binaries:
```
c:\np\cross\bin\x86-darwin>clang --version
clang version 5.0.1 (tags/RELEASE_501/final)
Target: i686-pc-windows-cygnus
Thread model: posix
InstalledDir: /cygdrive/c/progs/Embarcadero/XE7/bin
```
 but the very same error:
```
Compile package FCL 1.0.1: Success, Warnings: 1, Hints: 2
Hint: Start of reading config file C:\np\fpc\bin\i386-win32\fpc.cfg
Warning: Option "-Xr" is ignored for the current target platform.
Hint: End of reading config file C:\np\fpc\bin\i386-win32\fpc.cfg
Verbose: Free Pascal Compiler version 3.3.1-r40491 [2019/03/25] for x86_64
Verbose: Copyright (c) 1993-2018 by Florian Klaempfl and others
Verbose: Target OS: Darwin for x86_64
Verbose: Compiling fcllaz.pas
Verbose: Assembling fcllaz
Verbose: 21 lines compiled, 0.4 sec
Verbose: 1 warning(s) issued
Verbose: 2 hint(s) issued
Compile package LazUtils 1.0: Exit code 1, Errors: 1, Warnings: 2, Hints: 6
Hint: Start of reading config file C:\np\fpc\bin\i386-win32\fpc.cfg
Warning: Option "-Xr" is ignored for the current target platform.
Hint: End of reading config file C:\np\fpc\bin\i386-win32\fpc.cfg
Verbose: Free Pascal Compiler version 3.3.1-r40491 [2019/03/25] for x86_64
Verbose: Copyright (c) 1993-2018 by Florian Klaempfl and others
Verbose: Target OS: Darwin for x86_64
Verbose: Compiling lazutils.pas
Verbose: Compiling easylazfreetype.pas
....
Verbose: Assembling easylazfreetype
Debug: C:\np\lazarus\components\lazutils\lib\x86_64-darwin\easylazfreetype.s:8124:2: error: invalid instruction mnemonic 'cvtsi2ssl'
Debug:         cvtsi2ssl       %eax,%xmm0
Debug:         ^~~~~~~~~
easylazfreetype.pas(2227,0) Error: Error while assembling exitcode 1
easylazfreetype.pas(2227,0) Verbose: There were 2 errors compiling module, stopping
Verbose: Compilation aborted
Verbose: C:\np\fpc\bin\i386-win32\ppcrossx64.exe returned an error exitcode
```

There is something wrong with my setup.
As I wrote above, fpcupdeluxe was able to compile its packages for x86_64-darwin.
Only my Lazarus fails.

**Comment by LongDirtyAnimAlf** [comment] 2019-03-25 10:35
I am unable to reproduce unfortunately.

Do you (in Lazarus) perform a "Clean up and Build",  including the packages ?

**Comment by synopse** [comment] 2019-03-25 12:36
If I run the following:
```
c:\np\cross\bin\x86-darwin>clang --version
clang version 5.0.1 (tags/RELEASE_501/final)
Target: i686-pc-windows-cygnus
Thread model: posix
InstalledDir: /cygdrive/c/progs/Embarcadero/XE7/bin

c:\np\cross\bin\x86-darwin>clang-5.0.exe --version
clang version 5.0.1 (tags/RELEASE_501/final)
Target: i686-pc-windows-cygnus
Thread model: posix
InstalledDir: /x86-darwin
``` 
and on a place where it is working - from @mdbs99 :
``` 
W:\md\dev\proj\livemon\ide\cross\bin\x86-darwin>clang --version
This version of W:\md\dev\proj\livemon\ide\cross\bin\x86-darwin\clang.exe is not compatible with the version of Windows you're running. Check your computer's system information and then contact the software publisher.
``` 
so I guess there is indeed a confusion when Embarcadero is installed...
I will try to get rid of Embarcadero XE7 in my path...

**Comment by synopse** [comment] 2019-03-25 12:41
OK - I have just renamed my `c:\progs\Embarcadero\XE7\bin\clang.exe` and now... it compiles! :)

**Comment by mdbs99** [comment] 2019-03-25 13:09
That `clang.exe` seen that is just an "alias".
Calling either `clang-4.0.exe` or `clang-5.0.exe` works, as Arnaud already said.

**Comment by LongDirtyAnimAlf** [comment] 2019-03-26 07:47
Will try to prevent the tools to look into the path for clang !
Stay tuned.

**Comment by LongDirtyAnimAlf** [comment] 2019-03-26 09:57
I have uploaded new binary tools for Darwin cross on Windows.
These should not look in the path, if a local dedicated clang from fpcupdeluxe is available.
Please test.

**Comment by mdbs99** [comment] 2019-03-26 13:23
@synopse could you test it for us?

**Comment by LongDirtyAnimAlf** [comment] 2019-04-13 08:21
Closing. No feedback.
Re-open if needed !

**Closed by LongDirtyAnimAlf** 2019-04-13 08:21 UTC
