### ISSUE TITLE
module internettools does not compile

### ISSUE THREAD

**Issue by dkounal** [LongDirtyAnimAlf/fpcupdeluxe#265] opened 2020-07-09 10:03 UTC
I get when installing:
C:\fpcupdeluxe\ccr\internettools\lib\i386-win32\xquery__regex.ppu:xquery__regex.pas(80,12) Fatal: (10022) Can't find unit xquery__regex used by xquery
Fatal: (1018) Compilation aborted
Error: C:\fpcupdeluxe\fpc\bin\i386-win32\ppc386.exe returned an error exitcode
make[2]: *** [idepkg] Error 2
make[1]: *** [idepkg] Error 2
Error: (lazarus) Build IDE: stopped with exit code 2
Error: (lazarus) Building IDE: Building IDE failed.
make: *** [useride] Error 2

Following the advice from here: https://github.com/benibela/internettools/issues/9
I replace the origin from https://github.com/BeRo1985/flre/ tp https://github.com/benibela/flre/ but I still getting the some error
module fire installed without problems

**Comment by LongDirtyAnimAlf** [comment] 2020-07-09 10:24
I just tried to reproduce your issue.
Installing internettools on my win32 with FPC and Lazarus trunk succeeded without any problem !
So, we need more info.
FPC and Lazarus version. Fpcupdeluxe version.

**Comment by dkounal** [comment] 2020-07-09 10:45
I apologize:
FPC 3.2 stable FPCUPdeluxe 1.6.8y lazarus https://svn.freepascal.org/svn/lazarus/tags/lazarus_2_0_10

**Comment by LongDirtyAnimAlf** [comment] 2020-07-19 11:03
Would you mind testing the latest pre-release ?
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/tag/1.8.0b

It might be necessary to uninstall internettools first.

**Comment by LongDirtyAnimAlf** [comment] 2020-07-24 19:44
Closing due to no feedback.
Please re-open when necessary.

**Closed by LongDirtyAnimAlf** 2020-07-24 19:44 UTC

**Comment by dkounal** [comment] 2020-07-24 20:58
1.8.0e build 304
C:/fpcupdeluxe/fpc/bin/i386-win32/make -C ide idepkg
C:/fpcupdeluxe/fpc/bin/i386-win32/make --assume-new=lazarus.pp lazarus.exe OPT=' -WG @C:\fpcupdeluxe\config_lazarus\idemake.cfg'
C:/fpcupdeluxe/fpc/bin/i386-win32/fpc.exe -gl -vbqewnhi -Sci -dlclwin32 -Fu../designer -Fu../debugger -Fu../debugger/frames -Fu../converter -Fu../packager -Fu../packager/frames -Fu../components/custom -Fuinclude/win -Fuframes -Fu. -FuC:/fpcupdeluxe/fpcsrc/rtl -FuC:/fpcupdeluxe/fpcsrc/packages/paszlib -FuC:/fpcupdeluxe/fpcsrc/packages/fcl-process -FuC:/fpcupdeluxe/fpcsrc/packages/hash -FuC:/fpcupdeluxe/fpcsrc/packages/libtar -FuC:/fpcupdeluxe/fpcsrc/packages/fpmkunit -FuC:/fpcupdeluxe/fpcsrc/packages/regexpr -Fiinclude -Fiinclude/win32 -Fi../images -FE.. -FU../units/i386-win32/win32 -WG @C:\fpcupdeluxe\config_lazarus\idemake.cfg -di386 @C:\fpcupdeluxe\config_lazarus\idemake.cfg lazarus.pp
(1002) Target OS: Win32 for i386
(3104) Compiling lazarus.pp
(10001) PPU Loading C:\fpcupdeluxe\ccr\internettools\lib\i386-win32\internettools.ppu
(10011) PPU Source: internettools.pas not found
(10028) Recompiling internettools, checksum changed for C:\fpcupdeluxe\ccr\internettools\lib\i386-win32\bbutils.ppu
C:\fpcupdeluxe\config_lazarus\staticpackages.inc(1,1) Fatal: (10022) Can't find unit internettools used by Lazarus
Fatal: (1018) Compilation aborted
Error: C:\fpcupdeluxe\fpc\bin\i386-win32\ppc386.exe returned an error exitcode
make[2]: *** [idepkg] Error 2
make[1]: *** [idepkg] Error 2
Error: (lazarus) Build IDE: stopped with exit code 2
Error: (lazarus) Building IDE: Building IDE failed.
make: *** [useride] Error 2

fpcupdeluxe: ERROR: InternetToolsInstaller (ConfigModule: internettools): Failure trying to rebuild Lazarus. 
Details: 


ERROR: Fpcupdeluxe fatal error !
Sequencer (internettools): Failure running fpcupdeluxe: error executing sequence internettools
Sequencer (Only): Failure running fpcupdeluxe: error executing sequence Only

**Comment by LongDirtyAnimAlf** [comment] 2020-07-25 06:31
This is a problem of the internettools package itself. Some circular dependency that should be fixed by the maintainer.
Workaround: just click install module again. That should work.
