### ISSUE TITLE
v1,8,0e (dwn) : Error: (lazbuild) ?訡? for revision 'Unvesioned diectoy'

### ISSUE THREAD

**Issue by pult** [LongDirtyAnimAlf/fpcupdeluxe#289] opened 2020-07-26 04:27 UTC
Failed build lazarus when fpc compiled with revision "**Unvesioned diectoy**".
Reproduce steps:
1) fpcupdeluxe options:
[ ] Get FPC/Laz
[x] FPC/Laz rebuild only
2) build only FPS - OK : FPC revision "**Unvesioned diectoy**"
3) build only Laz - Failed. Error stack:

[TEnvironmentOptions.Load]  error reading "C:\fpcupdeluxe\config_lazarus\environmentoptions.xml": **Access violation**
  $004512D8  TLAZLOGGER__DEBUGLNSTACK,  line 891 of lazloggerbase.pas
  $0044F6BA  DEBUGLNSTACK,  line 11 of LazLoggerImpl.inc
  $004023A4  TLAZBUILDAPPLICATION__ONIDEMESSAGEDIALOG,  line 337 of lazbuild.lpr
  $006DD5DA  IDEMESSAGEDIALOG,  line 124 of idedialogs.pas
  $004EE788  TBUILDMANAGER__RESCANCOMPILERDEFINES,  line 1144 of buildmanager.pas
  $004F5DE1  TBUILDMANAGER__SETBUILDTARGET,  line 2908 of buildmanager.pas
  $004F60B9  TBUILDMANAGER__SETBUILDTARGETIDE,  line 2942 of buildmanager.pas
  $00403153  TLAZBUILDAPPLICATION__BUILDLAZARUSIDE,  line 581 of lazbuild.lpr
  $00406973  TLAZBUILDAPPLICATION__RUN,  line 1503 of lazbuild.lpr

=>> stack analyze:
    buildmanager.pas
    ================
        if not **FoundSystemPPU** then begin
          !!! ... ERROR ... !!!

After reset options:
[x ] Get FPC/Laz
[ ] FPC/Laz rebuild only
And rebuild FPC to revision **FRET_UNKNOWN_REVISION**- Laz is rebuild fine!
Notes: Acces Violation is always presented :(

All logs and config files in attached "laz_build_ifo_2020.0726_fpcupdeluxe_1,8,0e_i386-win32.zip"

[laz_build_ifo_2020.0726_fpcupdeluxe_1,8,0e_i386-win32.zip](https://github.com/LongDirtyAnimAlf/fpcupdeluxe/files/4977129/laz_build_ifo_2020.0726_fpcupdeluxe_1.8.0e_i386-win32.zip)

![laz_build_ifo_2020 0726_fpcupdeluxe_1,8,0e_i386-win32](https://user-images.githubusercontent.com/1542721/88471333-009e7600-cf11-11ea-889f-b85fcbf7554e.jpg)

**Comment by LongDirtyAnimAlf** [comment] 2020-07-26 08:12
I do not think this is related to fpcupdeluxe, but however.
An issue surely present is the unknown revision error.
Please test with a pre-release.
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/download/1.8.0f/fpcupdeluxe-i386-win32.exe

First, do a normal update (if possible), to reset all revision settings.
Then, perform a rebuild-only.

It might be that this issue is related to the revision error, but on my systems, I cannot reproduce your issue.

**Comment by pult** [comment] 2020-07-27 07:01
What is "normal update" ? It is without rebuild? I couldn't just update only without rebuilding. I do not see the mode - only updates.

**Comment by pult** [comment] 2020-07-28 07:48
1.8.0f - not solved

fpc 'Unvesioned diectoy' OK
laz 'Unvesioned diectoy' ERROR
laz FRET_UNKNOWN_REVISION ERROR
fpc FRET_UNKNOWN_REVISION OK
laz '+rebuild-only' OK
laz-'-rebuild-only' OK

logs:
[2020.0728.0715_v1.8.0f.zip](https://github.com/LongDirtyAnimAlf/fpcupdeluxe/files/4986731/2020.0728.0715_v1.8.0f.zip)

**Comment by LongDirtyAnimAlf** [comment] 2020-10-12 13:50
Would you please test the newest release ?
Thanks.
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/tag/1.8.2a

**Comment by LongDirtyAnimAlf** [comment] 2020-12-03 07:05
Closing due to no feedback.
Please re-open if needed.

**Closed by LongDirtyAnimAlf** 2020-12-03 07:05 UTC
