### ISSUE TITLE
Mac OS install and runtime issues a) Access Violation, b) doesn't seem to configure (Laz+FPC -> Ultibo)

### ISSUE THREAD

**Issue by AlanTheBeast** [LongDirtyAnimAlf/fpcupdeluxe#360] opened 2021-02-27 00:00 UTC
Installed, all okay.

1) On run, get this message

![image](https://user-images.githubusercontent.com/16036095/109367505-3ec39580-7864-11eb-9e5e-f775c6f349bd.png)

2) On selecting "Ultibo" and committing, get same message as above.

3) On selecting "FPC+Lax='thumbs up'", get same message as above.

4) After accepting the problem in any case, nothing appears to happen at all.

Sys info:
  System Version:	macOS 10.14.6 (18G103)
  Kernel Version:	Darwin 18.7.0
  Boot Volume:	Macintosh HD

**Comment by LongDirtyAnimAlf** [comment] 2021-02-27 05:55
Can you explain me what you mean with installing fpcupdeluxe ?
Its not meant to be installed. Its just a binary that has to be dropped inside a directory.
The best is to drop it into the directory where you want to install FPC and Lazarus.

![structure](https://user-images.githubusercontent.com/10783972/109376998-9267ca80-78c8-11eb-8ef7-dd7d2886c68e.JPG)

As you can see above, the target directory is stable32. Fpcupdeluxe itself is placed inside a subdir called up.
These two directories are created by the user. All others are created by fpcupdeluxe.

**Comment by LongDirtyAnimAlf** [comment] 2021-02-27 06:44
I just checked the installation of Ultibo on modern OSX. It fails due to the Lazarus version being to old.
So, Ultibo cannot be installed on Mac.

**Comment by LongDirtyAnimAlf** [comment] 2021-02-27 17:55
And.
There was a nasty bugger. So, a new release.
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/tag/1.8.2l

**Comment by AlanTheBeast** [comment] 2021-02-27 21:41
Downloaded and “copied” to the same folder where Lazarus is installed.

Same errors as previously reported at all three steps.

**Comment by LongDirtyAnimAlf** [comment] 2021-02-28 10:02
Can you please send me your fpcupdeluxe.ini files ?

**Comment by AlanTheBeast** [comment] 2021-02-28 13:20
No such file located in the folder where the app is located.  Finder can’t find it anywhere either.

**Comment by LongDirtyAnimAlf** [comment] 2021-03-02 06:48
> No such file located in the folder where the app is located.  Finder can’t find it anywhere either.

Well. There you have the source of this error.
Fpcupdeluxe must be able to create three (3) ini-files. All three in the same directory as where the app itself is located.
If this fails, nothing will work.
this is unexpected behavior.

**Comment by frogfather** [comment] 2021-03-22 13:10
Hello, I'm getting the same issue on both Mohave and Catalina. Executable is being run from downloads directory so permissions shouldn't be an issue. Version of fpcupDeluxe is v1.8.2m

**Comment by dexter4** [comment] 2021-06-17 01:30
Fpcupdeluxe does not run on macOS, it crashes when launching Fpcupdeluxe.
I have tried to run Fpcupdeluxe on: macOS 10.11 El Capitan, macOS 10.12 Siera, macOS 14.14 Mojave, macOS 14.15 Catalina.
Fpcupdeluxe crashes on all versions of macOS.
I have tried to run latest version of Fpcupdeluxe, and also tried to run earlier versions of Fpcupdeluxe (up to 5 steps backwards with version numbers) – all versions of Fpcupdeluxe crash on all versions of macOS.
Please fix the problem.

**Comment by michael-ring** [comment] 2021-06-17 06:07
I have successfully used fpcupdeluxe on my Mac for at least a year, works fine on m1 and on x86-64 with current versions and also older versions. 

I have created a directory in my home dir and then have copied fpcupdeluxe in this directory. After right-clicking the app and opening it from the popup it works like a  (m1 will need an extra step)

fpcupdeluxe must be able to write its config files, then it starts and works without hassle.

**Comment by dexter4** [comment] 2021-06-17 06:57
I have just downloaded and tested your latest file
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/download/1.8.2u/fpcupdeluxe-x86_64-darwin-cocoa.zipp
on macOS 10.11 El Capitan.
Unfortunately, your file does not work. The only new feature – now app does not display crash message as it was with earlier versions.
The app simply instantly silently closes and disappears after launching.
The problem has nothing to do with “zips as textfiles”, it has nothing to do with renaming to “zipp”, etc. The zip file extracts successfully, it extracts “fpcupdeluxe-x86_64-darwin-cocoa.app”, which however fails to run.
I suspect that your app uses some additional libraries, which are present on your computer however which are not present on other (clean) mac computers. When launching, the app fails to finds some dependent libraries and crashes. That is the most probable reason of crash.
This thread contains the same exact reports of crash from many people.
You should do clean install of macOS on your VM and you will see yourself that “fpcupdeluxe-x86_64-darwin-cocoa.app” crashes because of some missing dependent libraries. You need to find out which additional libraries are required. Just do the testing on clean newly installed mac computer.

**Comment by frogfather** [comment] 2021-06-17 07:58
Hi, I've found the following approach to work on mac: Catalina and Mohave. Not tried Big Sur.
1) clone the repo for the project locally and open it in your current version of Lazarus
2) you *may* see an error on loading about some missing properties of that multicoloured listbox (can't recall its exact name). If that happens locate these properties in fpcupdeluxemainform.lfm and delete them. This problem had gone away last time I tried so it may just work.
3) Build and run the project using your current version of Lazarus.

**Comment by LongDirtyAnimAlf** [comment] 2021-08-16 14:08
I am closing this issue as part of a cleanup of open issues that are more or less floating.
Please re-open when needed.

**Closed by LongDirtyAnimAlf** 2021-08-16 14:08 UTC

**Comment by thierrybo** [comment] 2021-11-14 23:07
> Hello, I'm getting the same issue on both Mohave and Catalina. Executable is being run from downloads directory so permissions shouldn't be an issue. Version of fpcupDeluxe is v1.8.2m

Apparently it is an issue. Visually the rights are equals but "Access violation" appears only in Download folder. A macOS "feature"!
